name: pyinstaller build

on:
  push:
  pull_request:

defaults:
  run:
    shell: bash

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        arch: [amd64]
    runs-on: ubuntu-latest
    container: 
      image: ubuntu:22.04
      options: --platform linux/${{ matrix.arch }}

    steps:
    - uses: actions/checkout@main
      with:
        fetch-depth: 1
    - name: install dependencies
      run: |
        apt-get update
        apt-get install -y curl sudo zip
        DEBIAN_FRONTEND=noninteractive TZ=Etc/UTC apt-get install -y python3-pyqt5 python3-pyqt5.qtchart \
          python3-numpy pip python3-yaml python3-psutil python3-boto3 python3-git
        curl https://raw.githubusercontent.com/unhuman-io/obot/main/install-obot.sh > install-obot.sh
        chmod +x install-obot.sh
        ./install-obot.sh --no-driver
        pip install pyinstaller gspread oauth2client paramiko
    - name: build with pyinstaller
      run: |
        export PYTHONPATH=/usr/share/motor-realtime/
        echo ${{ github.run_number }} > buildnum
        cat buildnum
        pyinstaller --hidden-import=PyQt5.sip --add-data="buildnum:." motor_gui.py
        zip -r dist.zip dist/
    - name: Archive production artifacts
      uses: actions/upload-artifact@main
      with:
        name: dist
        path: dist
    - uses: pyTooling/Actions/releaser@main
      if: contains(github.ref, 'main')
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        files: |
          ./dist.zip
        tag: main
